### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by kangwang1988** [felixblaschke/simple_animations#23]
Using the latest code, I met a problem when running it:
```shell
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Nexus 5 is available at: http://127.0.0.1:59333/919QW6nGJrA=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
E/flutter (21471): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _LoadStuffButtonState#40da8(lifecycle state: defunct, not mounted)
E/flutter (21471): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (21471): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (21471): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (21471): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1112:9)
E/flutter (21471): #1      State.setState (package:flutter/src/widgets/framework.dart:1147:6)
E/flutter (21471): #2      _LoadStuffButtonState._clickLoadStuff.<anonymous closure> (package:simple_animations_example_app/examples/load_stuff_button.dart:83:7)
E/flutter (21471): #3      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (21471): #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (21471): #5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (21471): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (21471): #7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (21471): #8      Future._complete (dart:async/future_impl.dart:514:7)
E/flutter (21471): #9      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
E/flutter (21471): #10     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (21471): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (21471): #12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (21471): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (21471): #14     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (21471): #15     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (21471): #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (21471): #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (21471): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (21471): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (21471): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (21471): 
```

**Comment by felixblaschke** [comment]
Fixed in 1.3.10
